meta_product_name: "Big-Family"
meta_title: "Big-Family: Découvre un avenir qui t'appartient."
meta_description: "On te donne tous les secrets de l’orientation et tu pourras te créer ton premier réseau. Rejoins la Big-Family et trouve des études, un métier et des potes. 💪"
meta_image: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1532951367/ogg.png"                       # should exist in `app/assets/images/`
  # required for Twitter Cards
