# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts 'Creating jobs...'
jobs = [
   {
     name: "GARDE D'ENFANT À DOMICILE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917629/kid4.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "ASSISTANTE MATERNELLE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917629/kid5.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "ASSISTANTE / ASSISTANT DE SERVICE SOCIAL",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917629/kid6.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
  {
    name: "AUXILIAIRE DE VIE SOCIALE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917629/kid7.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "CONSEILLER(ÈRE) EN INSERTION SOCIALE ET PROFESSIONNELLE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917630/friends2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "ASSISTANT INFORMATIQUE ET INTERNET À DOMICILE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917630/informatique1.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "ÉDUCATEUR(TRICE) SPÉCIALISÉ(E) ",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917630/kid1.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "PROTHÉSISTE ONGULAIRE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917630/nails.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "ENTRAÎNEUR(EUSE) SPORTIF(TIVE)",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917630/sport1.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "EDUCATEUR(TRICE) SPORTIF(TIVE)",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917630/sport2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
   {
     name: "SKIPPER",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917631/boat3.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "MONITEUR D'ACTIVITÉS NAUTIQUES",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917631/boat4.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "RADIOLOGUE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917631/radiologue.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
  {
    name: "MONITEUR DE SKI",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917631/ski.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "CHAUFFEUR DE VTC",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917631/vtc.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "MONITEUR DE VOILE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/boat2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "PSYCHIATRE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/brain.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "PSYCHOLOGUE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/brain.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "ASSISTANTE / ASSISTANT DENTAIRE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/dents.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "CHIRURGIEN(IENNE)-DENTISTE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/dents.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
   {
     name: "PROTHÉSISTE DENTAIRE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/dents.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "PÉDICURE - PODOLOGUE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/feet.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "SECRÉTAIRE MÉDICALE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/inf3.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
  {
    name: "KINÉSITHÉRAPEUTE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/kine.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "AUXILIAIRE DE PUÉRICULTURE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/pediatre.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "PÉDIATRE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/pediatre.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "PUÉRICULTRICE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/pediatre.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "PHARMACIEN / PHARMACIENNE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/pharmacy.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "PRÉPARATEUR(TRICE) EN PHARMACIE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/pharmacy.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "BRANCARDIER / BRANCARDIÈRE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/recherche2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
   {
     name: "CARDIOLOGUE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/recherche2.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "DERMATOLOGUE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/recherche2.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "ERGOTHÉRAPEUTE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/recherche2.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
  {
    name: "INGÉNIEUR EN RECHERCHE CLINIQUE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/recherche2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "MANIPULATRICE(TEUR)  D'ÉLECTRORADIOLOGIE MÉDICALE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/recherche2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "OPHTALMOLOGISTE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/recherche2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "OSTÉOPATHE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/recherche2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "PSYCHOMOTRICIEN / PSYCHOMOTRICIENNE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917632/recherche2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "AUXILIAIRE DE VIE SCOLAIRE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/aide.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "CONSEILLER(ÈRE) PRINCIPAL(E) D'ÉDUCATION",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/conseiller.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
   {
     name: "CONSEILLÈRE(ER) D'ORIENTATION - PSYCHOLOGUE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/conseiller.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "PSYCHOLOGUE SCOLAIRE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/conseiller.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "MÉDECIN",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/doc1.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
  {
    name: "ÉDUCATEUR(TRICE) TECHNIQUE SPÉCIALISÉE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/educ.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "FORMATEUR MULTIMÉDIA",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/educ.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "FORMATRICE / FORMATEUR",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/educ.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "TECHNICIEN(NE) DE L'INTERVENTION SOCIALE ET FAMILIALE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/family1.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "DÉVELOPPEUR HUMANITAIRE RURAL",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/humanity.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "DÉVELOPPEUR HUMANITAIRE URBAIN",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/humanity.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "SAGE-FEMME",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/inf1.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "INFIRMIÈRE - INFIRMIER",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/inf2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "CONDUCTEUR(TRICE) ROUTIER(TIÈRE)",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/truck.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "RESPONSABLE LOGISTIQUE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917633/truck2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
 {
   name: "COMMISSAIRE DE BORD",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917634/boat.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "CHERCHEUR / CHERCHEUSE",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917634/chercheur.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "COMMIS DE CUISINE",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917634/commis.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "CUISINIER / CUISINIÈRE",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917634/commis.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "CHEF DE COMPTOIR",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917634/counter.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "EMPLOYÉ DE RESTAURATION RAPIDE",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917634/fast_food.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "MAÎTRE DE CONFÉRENCES",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917634/teacher.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "PROFESSEUR D'ÉDUCATION PHYSIQUE ET SPORTIVE",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917634/teacher.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 }
]
jobs.each do |job|
  new_job = Job.new(job)
  new_job.remote_photo_url = job[:photo]
  new_job.save
end

puts 'Finished!'



