# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts 'Creating jobs...'
jobs = [
   {
     name: "ELECTRICIEN DE MAINTENANCE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917129/electricien.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "GAME DESIGNER",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917129/gaming.jpgLEVEL DESIGNER",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "LEVEL DESIGNER",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917129/gaming.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
  {
    name: "PRODUCER",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917129/gaming.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "SCRIPTE DE JEUX VIDÉO",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917129/gaming.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "TESTEUR / TESTEUSE DE JEUX VIDÉO",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917129/gaming.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "INGÉNIEUR AÉRONAUTIQUE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917129/plane3.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "INGÉNIEUR DE PRODUCTION",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917129/production2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "WEBMASTER",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917129/webmaster.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "DATA ANALYST / DATA SCIENTIST",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917130/data.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
   {
     name: "CONTRÔLEUR EN ÉLECTRICITÉ ET ÉLECTRONIQUE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917130/electricite.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "TRAFFIC MANAGER",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917130/traffic.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "DÉPANNEUR TV ÉLECTROMÉNAGER",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917130/tv.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
  {
    name: "TECHNICIEN(NE) IMPRIMANTE 3 D",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917132/3Dprint.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "BOBINIER",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917226/bobinier.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "CONSULTANT TECHNIQUE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917226/idea.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "AUTOMATICIEN",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917226/industry.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "INGÉNIEUR DE FABRICATION MÉCANIQUE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917226/industry.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "INGÉNIEUR LEAN",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917226/industry.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "OPÉRATEUR RÉGLEUR SUR MACHINE AUTOMATISÉE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917226/industry.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
   {
     name: "TECHNICIEN DE MAINTENANCE INDUSTRIELLE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917226/industry.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "CHEF DE PROJET INFORMATIQUE",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917226/informatique.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "TUYAUTEUR",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917226/pipe2.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
  {
    name: "CONDUCTEUR DE LIGNE DE PRODUCTION ALIMENTAIRE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917226/production.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "CHAUDRONNIER TÔLIER",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917226/tolier.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "CHARPENTIER DE MARINE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917227/boat9.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "RESPONSABLE HYGIÈNE, SÉCURITÉ, ENVIRONNEMENT",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917227/security.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "PÉPINIÉRISTE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917227/tree8.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "RESPONSABLE DE SECTEUR DANS UN ESPACE NATUREL",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917227/tree9.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "RUDOLOGUE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917227/waste.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
   {
     name: "TECHNICIEN TRAITEMENT DÉCHETS",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917227/waste.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "TECHNICIEN DE LA QUALITÉ DE L'EAU",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917227/water5.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "TECHNICIEN EAU ET INSTALLATIONS SANITAIRES",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917227/water5.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
  {
    name: "HYDROGÉOLOGUE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917227/wter2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "EBOUEUR",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917228/eboueur.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "JARDINIER DE GOLF",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917228/golf.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "HYDRAULICIEN",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917228/hydraulicien.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "CONDUCTEUR DE STATION D'ÉPURATION",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917228/water.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "BÛCHERON",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917228/wood2.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "PACKAGER ÉDITORIAL",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917255/book3.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
   {
     name: "SECRÉTAIRE D'ÉDITION",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917255/book4.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "SECRÉTAIRE DE RÉDACTION",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917255/book5.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
   {
     name: "DIRECTEUR(TRICE) DE COLLECTION (EDITION)",
     photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917255/book6.jpg",
     synonym: "",
     short_description: "",
     description: "",
     study: "",
     salary: "",
     career: "",
     similar_job: [ "", "", "", "", ""],
     interest: [""],
     statut: ""
   },
  {
    name: "ANIMATEUR ENVIRONNEMENT",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917255/breathe.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "ECO-CONSEILLER",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917255/breathe.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "ECOTOXICOLOGUE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917255/breathe.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "TECHNICIEN DE FABRICATION",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917255/comm15.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "CORRECTEUR / CORRECTRICE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917255/correct.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "ILLUSTRATEUR",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917255/illustrateur.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "MAQUETTISTE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917255/maquettiste.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "CONDUCTEUR DE PRESSE NUMÉRIQUE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917255/presse.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "CONDUCTEUR DE PRESSE OFFSET",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917255/presse.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
  {
    name: "DIRECTEUR DE CLIENTÈLE",
    photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917256/directeur.jpg",
    synonym: "",
    short_description: "",
    description: "",
    study: "",
    salary: "",
    career: "",
    similar_job: [ "", "", "", "", ""],
    interest: [""],
    statut: ""
  },
 {
   name: "DOCUMENTALISTE",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917256/documentaliste.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "CHARGÉ DE MISSION PATRIMOINE CULTUREL",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917256/events.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "ASSISTANT / ASSISTANTE DE COMMUNICATION",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917256/events2.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "CHEF D'ATELIER DES INDUSTRIES GRAPHIQUES",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917256/print2.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "CHEF DE FABRICATION DES INDUSTRIES GRAPHIQUES",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917256/printing1.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "CHEF DE PROJET NUMÉRIQUE ÉDITION",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917256/website.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "STÉNOTYPISTE DE CONFÉRENCES",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917256/write.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 },
 {
   name: "DESSINATEUR DE PRESSE",
   photo: "http://res.cloudinary.com/dozkmkl7p/image/upload/v1526917257/dessinateur.jpg",
   synonym: "",
   short_description: "",
   description: "",
   study: "",
   salary: "",
   career: "",
   similar_job: [ "", "", "", "", ""],
   interest: [""],
   statut: ""
 }
]
jobs.each do |job|
  new_job = Job.new(job)
  new_job.remote_photo_url = job[:photo]
  new_job.save
end

puts 'Finished!'



